version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: org.springdoc:springdoc-openapi-security
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: org.springdoc:springdoc-openapi-common
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: org.springdoc:springdoc-openapi-ui
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.cucumber:cucumber-java
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.9.1
  - dependency-name: io.cucumber:cucumber-junit
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.9.1
  - dependency-name: io.cucumber:cucumber-spring
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.9.1
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: net.masterthought:cucumber-reporting
    versions:
    - 5.4.0
    - 5.5.2
  - dependency-name: io.fabric8:docker-maven-plugin
    versions:
    - 0.34.1
