name: Integration

on:
  push:
    branches:
      - develop

jobs:

  verify-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - name: Get release
      id: get_release
      run: echo ::set-output name=RELEASE_HTTP_CODE::$(curl -s -o out.html -w '%{http_code}'  https://github.com/les-projets-cagnottes/core/releases/tag/${{ steps.get_version.outputs.VERSION }};)
    - name: Test release existence
      run: if [[ "${{ steps.get_release.outputs.RELEASE_HTTP_CODE }}" -eq "200" ]]; then exit 1; else exit 0; fi

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: ./mvnw -B clean install --file pom.xml -P docker

  cucumber:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Test with Maven
      id: tests_run
      run: echo ::set-output name=EXIT_CODE::$(./mvnw -B clean test --file pom.xml > test.log ; echo $?)
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - name: Generate Cluecumber report
      run: ./mvnw -B cluecumber-report:reporting --file pom-cluecumber.xml
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: les-projets-cagnottes/les-projets-cagnottes.github.io
        token: ${{ secrets.GITHUB_IO_PAT }}
        path: les-projets-cagnottes.github.io
    - name: Clean previous version
      run: rm -rf les-projets-cagnottes.github.io/cucumber/${{ steps.get_version.outputs.VERSION }}
    - name: Prepare Cucumber output directory
      run: mkdir -p les-projets-cagnottes.github.io/cucumber/${{ steps.get_version.outputs.VERSION }}
    - name: Copy Cucumber Report
      run: cp -r target/cluecumber/* les-projets-cagnottes.github.io/cucumber/${{ steps.get_version.outputs.VERSION }}
    - name: Publish https://les-projets-cagnottes.github.io/cucumber/${{ steps.get_version.outputs.VERSION }}
      run: |
        cd les-projets-cagnottes.github.io
        git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}" && git config user.name "${{ secrets.GIT_CONFIG_NAME }}"
        git status
        git add .
        git commit --allow-empty -m "Update Cucumber for version '${{ steps.get_version.outputs.VERSION }}'"
        git push
        exit ${{ steps.tests_run.outputs.EXIT_CODE }}

  publish-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: ./mvnw -B clean install --file pom.xml -P docker
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - uses: sjdonado/heroku@0f16401029a67519b6547af7247983640996393a
    - name: Tag the image for GitHub Registry
      run: docker tag core:latest docker.pkg.github.com/les-projets-cagnottes/core/core:${{ steps.get_version.outputs.VERSION }}
    - name: Login to GitHub Registry
      run: docker login docker.pkg.github.com -u thomah -p ${{secrets.GITHUB_TOKEN}}
    - name: Publish to GitHub Registry
      run: docker push docker.pkg.github.com/les-projets-cagnottes/core/core:${{ steps.get_version.outputs.VERSION }}
    - name: Tag the image for Docker Hub
      run: docker tag core:latest lesprojetscagnottes/api:${{ steps.get_version.outputs.VERSION }}
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to Docker Hub
      run: docker push lesprojetscagnottes/api:${{ steps.get_version.outputs.VERSION }}
  
  deploy-heroku:
    needs: publish-docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - uses: sjdonado/heroku@0f16401029a67519b6547af7247983640996393a
    - name: Login to Registry
      run: docker login docker.pkg.github.com -u thomah -p ${{secrets.GITHUB_TOKEN}}
    - name: Pull Docker Image
      run: docker pull docker.pkg.github.com/les-projets-cagnottes/core/core:${{ steps.get_version.outputs.VERSION }}
    - name: Tag the image
      run: docker tag docker.pkg.github.com/les-projets-cagnottes/core/core:${{ steps.get_version.outputs.VERSION }} registry.heroku.com/les-projets-cagnottes-api/web
    - name: Get Heroku Tools
      run: wget -qO- https://toolbelt.heroku.com/install.sh | sh
    - name: Login to Heroku Registry
      run: echo "${{secrets.HEROKU_PASSWORD}}" | docker login -u "${{secrets.HEROKU_USERNAME}}" --password-stdin registry.heroku.com
    - name: Login to Heroku API
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_PASSWORD}}
    - name: Publish to Heroku Registry
      run: docker push registry.heroku.com/les-projets-cagnottes-api/web
    - name: Release Heroku app
      run: heroku container:release web --app les-projets-cagnottes-api
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_PASSWORD}}
